import os
from langchain_google_genai.chat_models import ChatGoogleGenerativeAI
from dotenv import load_dotenv
load_dotenv()

os.environ["GOOGLE_API_KEY"] =os.getenv("GOOGLE_API_KEY") or ""
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash")

def RefineTheAgentResponce(query : str , responce : str):
    messages = [  
    ("system", "You Are A HelpFul Agent And Its your duty to refine and modify the responce generated by the sql agent into more readable and in a natural human language . I will provide the query that the user has asked the sql agent and also i will give the generated responsce , Please convert that into more clear and efficient human readable form so that it conveys the message to humans in there language.Just give the refined & modified answer don't include any other things."),  
    ("human", f"here the query {query} and here the responce generated by the agent {responce}"),  
    ]  
    return llm.invoke(messages).content
